# Generated by Django 4.1.7 on 2023-02-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('DemandeId', models.AutoField(primary_key=True, serialize=False)),
                ('ClientId', models.IntegerField()),
                ('Montant', models.IntegerField()),
                ('Status', models.CharField(max_length=100)),
                ('But', models.CharField(max_length=100)),
            ],
        ),
    ]
