# Generated by Django 4.1.7 on 2023-02-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent_de_verification',
            fields=[
                ('idAgent_de_verification', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=500)),
                ('Prenom', models.CharField(max_length=500)),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
